// user
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

// multipleArticles
export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';

// singleArticle
export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE ';

export const HANDLE_LIKE_ARTICLE_REQUEST = 'HANDLE_LIKE_ARTICLE_REQUEST';
export const HANDLE_LIKE_ARTICLE_SUCCESS = 'HANDLE_LIKE_ARTICLE_SUCCESS';
export const HANDLE_LIKE_ARTICLE_FAILURE = 'HANDLE_LIKE_ARTICLE_FAILURE';

export const CLEAN_ARTICLE = 'CLEAN_ARTICLE ';
